project:
  type: book

book:
  title: "The Learn-It-All Educator"
  subtitle: "A Guidebook for Training Brains, Not Replacing Them with AI"
  author: "Dr. Szymon Machajewski"
  date: "Mar 15, 2026"
  description: "Rethinking AI in Higher Education"
  chapters:
    - index.qmd
    - chapters/02_introduction.md
    - chapters/03_chapter1.md
    - chapters/04_chapter2.md
    - chapters/05_chapter3.md
    - chapters/06_chapter4.md
    - chapters/07_backmatter.md

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    link-external-icon: true
    link-external-newpage: true
    from: markdown+autolink_bare_uris
  pdf:
    toc: true
    number-sections: false
    colorlinks: true
    papersize: b5
    documentclass: scrbook
    classoption:
      - DIV=14
      - BCOR=12mm
      - fontsize=10pt
    mainfont: "Georgia"
    sansfont: "Helvetica Neue"
    monofont: "JetBrains Mono"
include-in-header:
      text: |
        \usepackage{ragged2e}
        \setlength{\parindent}{0pt}
        \setlength{\parskip}{5pt}
        \raggedright
        \usepackage{graphicx}
        \usepackage{titling}
        \pretitle{
          \begin{center}
          \includegraphics[width=0.6\textwidth]{cover.png}\\[1em]
          \LARGE\bfseries
        }
        \posttitle{\end{center}}